### ISSUE TITLE
绘制并描述系统各个部件的术语与关系

### ISSUE THREAD

**Issue by skyjia** [reponote/pm#1]
- 客户端
- 前端
- 后端
- 前台
- 后台

作业内容
- [x] 完成绘图
- [x] 能够复述清晰相关概念

**Comment by Momobai531** [comment]
- 客户端：所有用户可以看得见摸得到的设备、系统以及程序都属于客户端，其中比较特别的还有浏览器；
- 前端：用户进入系统后接触到的第一层程序，比如可以通过浏览器打开H5或Web进行阅读或操作，这个H5和Web就是前端；另外前端还包括API；
- 后端：用户在互联网上看不见的地方属于后端，比如数据库；
- 前台：所有给用户使用的程序都属于前台范畴，其中包含客户端程序、前端程序；
- 后台：所提供程序的内部运营人员或管理人员使用的系统或程序。

**Comment by Momobai531** [comment]
![Uploading 屏幕快照 2016-03-16 下午3.41.46.png…]()

**Comment by Momobai531** [comment]
![2016-03-16 3 41 46](https://cloud.githubusercontent.com/assets/17847882/13806020/d5a04452-eb93-11e5-87ab-5a6324bd3d19.png)

**Comment by skyjia** [comment]
浏览器应该是属于客户端程序

**Comment by Momobai531** [comment]
![2016-03-16 4 44 43](https://cloud.githubusercontent.com/assets/17847882/13806504/fb517a60-eb96-11e5-95ff-955656844e9c.png)

**Comment by skyjia** [comment]
这回对了

**Comment by skyjia** [comment]
:8ball:
