### ISSUE TITLE
画TOWN应用的页面结构图

### ISSUE THREAD

**Issue by skyjia** [reponote/pm#10]

**Comment by Momobai531** [comment]
![1 pic](https://cloud.githubusercontent.com/assets/17847882/14075749/52283d26-f50e-11e5-93d7-ccb53a3c2cbd.jpg)
![2 pic](https://cloud.githubusercontent.com/assets/17847882/14075750/5229de10-f50e-11e5-8266-24edfec7b3fd.jpg)

**Comment by EthanCai** [comment]
方框中应该是页面，不应该是动作。如果要表示动作，应该写在连线上。

**Comment by EthanCai** [comment]
下一步：将纸质的导航图，用OmniGraffle画出来，作为下次培训内容的一部分。

**Comment by Momobai531** [comment]
![2016-03-31 5 46 25](https://cloud.githubusercontent.com/assets/17847882/14172106/027af496-f769-11e5-8e20-7efb6d783119.png)
