### ISSUE TITLE
阅读：产品经理需要了解的指标

### ISSUE THREAD

**Issue by skyjia** [reponote/pm#15]
http://www.jianshu.com/p/61dd1037532e
http://www.woshipm.com/operate/56362.html

**Comment by EthanCai** [comment]
补充一篇文章：http://www.woshipm.com/discuss/297903.html

下图是产品各阶段关注指标：
![](http://image.woshipm.com/wp-files/2016/03/336.png)

**Comment by EthanCai** [comment]
- Awareness认识阶段：
  - SOV：Share of voice，广告占有率，https://www.wikiwand.com/en/Share_of_voice
  - PFP：Pay-For-Performance，按业绩收费的模式。http://baike.baidu.com/view/637501.htm
  - PPC：Pay per click，同CPC，https://www.wikiwand.com/en/Pay_per_click
  - CPM：cost per impression，按千次展示付费，指通过某一媒体投放广告，听到或看到此广告的人达到一千人平均所要花费的广告费用。    
  - CPC：cost per click，按点击量付费，对某一广告点击所产生的广告费用，统计点击量可以设定一定标准，比如对于同一个IP，在一个时间段内重复点击，统计为一次，也可忽略IP的限制，直接统计总点击量。
- Growth增长阶段：
- Engagement交战阶段：
  - DAU：Daily Active User，日活跃用户
  - MAU: Monthly Active User，月活跃用户
- Monetization货币化阶段：
  - Rev：收入
- Resurrection复兴阶段：
  - Dormant Users：休眠用户
