### ISSUE TITLE
作业：设计火车票

### ISSUE THREAD

**Issue by EthanCai** [reponote/pm#17]
![image](https://cloud.githubusercontent.com/assets/286882/14147073/a532c418-f6cc-11e5-99b1-11975d6a37db.png)

@Momobai531 把完成设计贴上来吧。

**Comment by Momobai531** [comment]
![2016-03-27 8 56 11](https://cloud.githubusercontent.com/assets/17847882/14172146/29cc94b4-f769-11e5-937c-1ed652c74a47.png)

**Comment by Momobai531** [comment]
![2016-03-27 9 59 42](https://cloud.githubusercontent.com/assets/17847882/14172161/3888038a-f769-11e5-85a5-8b28390c7650.png)

**Comment by EthanCai** [comment]
:+1:
