### ISSUE TITLE
iOS类型应用产品分析 - 5个

### ISSUE THREAD

**Issue by Momobai531** [reponote/pm#2]

**Comment by Momobai531** [comment]
1. 摄影与录像类：MIX滤镜大师
  MIX是camera360旗下的一款免费图片编辑工具，不仅丰富了360相机品牌产品，在与品牌下的同类产品相比，其简单专注的图片处理方法吸引了一群对图片编辑有高要求的用户群体，并逐步引导用户下载使用旗下其他应用。MIX的主要功能是能够为用户免费提供百种类同于单反相机可以拍摄出的滤镜场景选择，更加专业细致的美化类别及参数调整选择，其次为用户提供了自定义滤镜场景选择，社区化公开展示，让用户能够体验更加开放且人性化的选择机会。
![2016-03-16 6 04 49](https://cloud.githubusercontent.com/assets/17847882/13808547/9bbf157a-eba1-11e5-8a1f-86624f2ff3e3.png)

2. 健康类： nike+running 
nike+running是nike.inc旗下一款专注跑步项目的智能应用，在用户免费下载和在移动设备端体验应用功能的过程中引导用户对品牌的喜好度，并逐渐将用户引流到购买nike相关产品的网络商店中，为用户提供运动一体式的服务。尤其在连接applewatch上会提供最新的功能体验，为跑步爱好者提供了准确的数据追踪和分析推荐功能，其次也增添了跑步爱好者社区，用户可以在社区中进行互动展示，保持和提高了用户的跑步积极性。
![2016-03-16 6 51 08](https://cloud.githubusercontent.com/assets/17847882/13809920/1f30301e-eba8-11e5-87a5-15692fe42c49.png)

3. 效率类：奇妙清单
奇妙清单是一款待办事项处理工具，帮助不同领域的用户群体规划任务清单，为生活、学习及工作等方面提高了时间效率。此款效率工具分为免费版和专业版，免费版主要提供基础性的任务清单设置和提醒，保证用户们的基础性需求，专业版则更适用于商业人士和学术人士，需要在线购买升级账户，在基础任务规划的基础上增添了文档、分配任务等功能。
![2016-03-16 8 14 33](https://cloud.githubusercontent.com/assets/17847882/13811908/b9c2f9c6-ebb3-11e5-934a-6f2798685878.png)

4. 美食类：豆果美食
豆果美食是一个接地气的生活美食类应用平台，对于喜爱分享美食和有学习美食做法需求的用户来说，豆果不仅提供了免费的学习平台，也同时拥有社交、电商支付以及第三方合作的业务模式。用户们可以自发上传原创美食及制作过程，形式包括菜谱或者视频，并且提供了评论及第三方分享功能，在社群中建立不同主题的互动活动，增强交流和用户体验，提高了用户们对豆果美食的忠诚度，从而引导用户们在豆果商城中购买新鲜事物。而第三方既可以在豆果平台上投放广告，也可以通过主题专栏的合作方式进行宣传且更易让用户们接受。
![2016-03-16 8 51 24](https://cloud.githubusercontent.com/assets/17847882/13812764/f536b56a-ebb8-11e5-8953-c2bec7298efb.png)

5. 生活类：豆瓣
豆瓣是一个提供参考价值信息和分享趣闻趣事的社交应用平台。用户主要集中在80后和90后人群中，平台主要以不同话题、主题的社区小组进行社交，以及书影音等类别的推荐及评价的模式提供内容，并可以通过第三方平台在线购买相关产品。在社区运营中，用户既可以找到相同爱好的人或事并进行互动交流，也可以自主创建话题参与评论回复；而在产品主题类的信息推荐中，用户可以通过搜索查询，阅读，以及点评信息参与评论，也可以通过平台推荐的不同渠道链接选择性购买产品。
![2016-03-16 9 38 59](https://cloud.githubusercontent.com/assets/17847882/13814013/88bf58c2-ebbf-11e5-929e-fd98d4a15da5.png)

**Comment by skyjia** [comment]
关于豆瓣的发展史，可以在知乎中搜一下，了解这类应用的演变过程。

**Comment by skyjia** [comment]
LGTM

**Comment by Momobai531** [comment]
1.旅行类：途牛旅游
途牛旅游是一个为旅行爱好者提供的社交应用平台。主要提供三个模块业务，一个是境外游，一个是境内游，另一个是周边游，用户可以根据自己的需求精准选择不同区域模块，参考第三方服务商提供的产品列表。用户既可以通过基础搜索和筛选进行需求匹配，而且在此基础上途牛提供了基于不同地点旅游的一条龙服务介绍和提供，用户可以直接跳转到第三方服务商官网进行购买，途牛也提供了不同主题的社区小组，方便用户参考信息和交流。
![2016-03-20 2 26 45](https://cloud.githubusercontent.com/assets/17847882/13903122/d37efa94-eea7-11e5-875f-2933878295a2.png)

2. 音乐类：Figure
Figure是Allihoopa旗下的一款随走随做的音乐制作工具，对于音乐创作者来说只需要用手指就可以完成音乐节奏的创造， 并且页面功能简单明了，通过提供的不同乐器的声效和混音工功能可以轻松录制出一首歌曲，不管是新手还是音乐经验者来说都是非常实用的。
![2016-03-20 2 47 25](https://cloud.githubusercontent.com/assets/17847882/13903167/b14e72d0-eeaa-11e5-8ecd-9350dc7b1b92.png)

3. 体育类：新浪体育
新浪体育是新浪旗下专注各项体育赛事和咨询的社交应用平台，喜爱体育的爱好者可以在这里选择观看赛事直播或阅读相关资讯的报道，也可以通过社区进行话题交流，其次平台也承接了第三方广告合作获取了一定盈利。赛事观看既可以直播也提供点播功能，用户可以轻松在线定制观赏自己喜欢的团队比赛，并且在有权利在新闻或者社区中提交自己的评论观点，获取相同认可。
![2016-03-20 3 03 58](https://cloud.githubusercontent.com/assets/17847882/13903212/072baa0e-eead-11e5-8771-567dd68f6bf4.png)

4. 商务类：WPS OFFICE
WPS是国内金山旗下的一款免费商务办公工具，是既微软office软件之后的另一款常用办公软件，在提供wording、excellent、PPT及PDF等常用文档格式的编辑与阅读以外，用户可以通过各类第三方平台进行文档传送和分享，利用云服务在线管理自己的文档。在编辑和管理文档的基础功能以外，同时支持不同设备之间的同步播放。
![2016-03-20 3 19 35](https://cloud.githubusercontent.com/assets/17847882/13903275/300343ea-eeaf-11e5-840b-f4e7574f7254.png)

5. 新闻类：网易新闻
网易新闻是网易旗下一款免费提供社会及生活时事资讯的移动应用平台，主要提供不同社会类别相关的新闻报道及定制化话题社区运营，并且衍生出第三方提供的热门话题帖子推荐。在新闻方面，用户既可以以文字、视频及电台等不同形式进行阅读，并且可以进行跟帖评论，在社区运营中，用户可以自主定制不同类别的生活话题并进行编辑及在线交流，也可以参与官方专栏跟帖，而在推荐业务中也同时承接不同内容及形式的合作。
![2016-03-20 3 36 17](https://cloud.githubusercontent.com/assets/17847882/13903350/842e9e72-eeb1-11e5-8d4b-6435a432a9c7.png)

**Comment by skyjia** [comment]
LGTM
