### ISSUE TITLE
复述非功能性需求有哪些，各自分类下具体举例说明

### ISSUE THREAD

**Issue by Momobai531** [reponote/pm#3]
直接写这里

**Comment by Momobai531** [comment]
常见的非功能性需求：
1. 交互性需求 
  - 是以内容提供为主要业务模式还是以运营模式...
  - 整体风格定位等
2. 性能
  - 注册或登陆验证码传送是否及时
  - 是否在实现预期功能下支持一些特殊需求，例如GPS搜索范围扩大
3. 稳定性和可用性
  - 使用某个程序功能时是否闪跳
  - 使用交互动作时是否有反应
4. 易用性（针对特殊人群）
  - 颜色搭配是否方便色盲人群观看使用
  - 小型移动智能携带设备是否能感应左撇子用户的使用动作等
5. 多语言（字符长度的设置、支持多语言切换等）
  - CJK字体问题，例如中文中的简繁体在不同字体中显示是否美观和可以辨认
  - 字符级：emoji，例如一个emoji等于多少个中文字符和多少个英文字符
6. 使用环境
  - 网络环境：在WIFI\4G\3G\2G等不同网络环境下的支持使用情况，例如是否都支持图片传送或打开视频
  - 地域环境：国内外、港澳台、国内不同地区等不同地理区域下，例如受时差影响是否保证同步翻译或字幕功能
  - 特殊使用环境：有无耳麦、话筒等不同场景选择；低电耗；不同操作系统，例如 在手机插入耳麦听歌时因为意外情况耳麦脱落，手机是否暂停播放音乐功能；低电耗的情况下是否支持声音传送或图片传送等功能

**Comment by Momobai531** [comment]
常见的非功能性需求：
- 交互性需求
 - 是以内容提供为主要业务模式还是以运营模式...
 - 整体风格定位等
- 性能
 - 注册或登陆验证码传送是否及时
 - 是否在实现预期功能下支持一些特殊需求，例如GPS搜索范围扩大
- 稳定性和可用性
 - 使用某个程序功能时是否闪跳
 - 使用交互动作时是否有反应
- 易用性（针对特殊人群）
 - 颜色搭配是否方便色盲人群观看使用
 - 小型移动智能携带设备是否能感应左撇子用户的使用动作等
- 多语言（字符长度的设置、支持多语言切换等）
 - CJK字体问题，例如中文中的简繁体在不同字体中显示是否美观和可以辨认
 - 字符级：emoji，例如一个emoji等于多少个中文字符和多少个英文字符
6. 使用环境
 - 网络环境：在WIFI\4G\3G\2G等不同网络环境下的支持使用情况，例如是否都支持图片传送或打开视频
 - 地域环境：国内外、港澳台、国内不同地区等不同地理区域下，例如受时差影响是否保证同步翻译或字幕功能
 - 特殊使用环境：有无耳麦、话筒等不同场景选择；低电耗；不同操作系统，例如 在手机插入耳麦听歌时因为意外情况耳麦脱落，手机是否暂停播放音乐功能；低电耗的情况下是否支持声音传送或图片传送等功能

**Comment by skyjia** [comment]
```
交互性需求
是以内容提供为主要业务模式还是以运营模式...
```

这个是商业模式，不属于交互性需求。

**Comment by skyjia** [comment]
`GPS搜索范围扩大` 怎么和性能有关？
是搜索扩大后能不能及时返回结果吧？？

**Comment by Momobai531** [comment]
交互性需求——整体的页面设计布局风格
性能——公交实时情况是否准确

**Comment by skyjia** [comment]
性能不是说什么东西够`准确`，是够不够快。
应该说：公交实时情况能不能`及时`更新。
说的时候用词要强调时效性。
