### ISSUE TITLE
绘制本周四课程内容的脑图，并用自己语言复述出来

### ISSUE THREAD

**Issue by skyjia** [reponote/pm#8]
要点：
- 金字塔结构
- 调理顺序比说的内容本身重要
- 专业术语在复述前一定要理解定义，含糊不清的考虑上网查资料或者直接问
- 排除一些模凌两可的专业术语或概念的理解
- 尝试用举例子的方式来复述理论知识点

**Comment by Momobai531** [comment]
![2016-03-20 4 36 47](https://cloud.githubusercontent.com/assets/17847882/13903652/71d168d2-eebf-11e5-97fd-4cc3edfad832.png)
![2016-03-20 4 52 59](https://cloud.githubusercontent.com/assets/17847882/13903654/71d65c66-eebf-11e5-9b35-8989fa5ea3f1.png)
![2016-03-20 5 14 49](https://cloud.githubusercontent.com/assets/17847882/13903651/71d095ec-eebf-11e5-9d19-7c205ea7cb24.png)
![2016-03-20 5 14 58](https://cloud.githubusercontent.com/assets/17847882/13903653/71d6435c-eebf-11e5-8a38-1c728e56d3f9.png)

**Comment by skyjia** [comment]
LGTM 除了错别字～ :smiley_cat:

**Comment by Momobai531** [comment]
![2016-03-23 4 28 07](https://cloud.githubusercontent.com/assets/17847882/13979597/84704858-f114-11e5-9569-75f9fef345fc.png)
![2016-03-23 4 28 30](https://cloud.githubusercontent.com/assets/17847882/13979598/8476f446-f114-11e5-9153-7a029b9c8b0f.png)
![2016-03-23 4 29 01](https://cloud.githubusercontent.com/assets/17847882/13979599/84eaf774-f114-11e5-83c4-4a16c93ad5ba.png)

**Comment by skyjia** [comment]
支付宝没有虚拟货币发行。这个是银监会禁止的行为。
所有互联网产品可以售卖各种币，但必须是单向的，否则违法。即，可以用法定货币购买虚拟资产内容，但虚拟资产内容不能以任何形式换回法定货币。

**Comment by skyjia** [comment]
脑图里面没有提到埋点

**Comment by Momobai531** [comment]
我写的买点
